#!/usr/bin/env r
## Regenerates inst/tinytest/fixtures/uss-origin-tuples.tsv from the
## installed ubuntu-security-status source, via tree-sitter. Run manually
## from the package root when update-manager-core changes:
##
##     r tools/make-uss-fixture.R
##
## Tree-sitter tooling stays behind this fixture boundary (see the Phase 1
## contracts in cornball-ai/runix): the package never depends on it, and
## the committed fixture is the only artifact tests read. Regenerating
## after an Ubuntu update shows classification drift as a plain diff.

stopifnot(
    requireNamespace("bonsaisitter", quietly = TRUE),
    requireNamespace("treesitter.python", quietly = TRUE)
)

src_path <- "/usr/bin/ubuntu-security-status"
lang <- treesitter.python::language()
src <- paste(readLines(src_path, warn = FALSE), collapse = "\n")
root <- bonsaisitter::tree_root_node(bonsaisitter::text_parse(src, lang))

q <- bonsaisitter::query(lang,
    "(assignment left: (identifier) @name right: (tuple) @tuple)")
ca <- bonsaisitter::query_captures(q, root)
nm <- vapply(ca$node[ca$name == "name"], bonsaisitter::node_text, character(1))
tv <- vapply(ca$node[ca$name == "tuple"], bonsaisitter::node_text, character(1))
stopifnot(length(nm) == length(tv))

keep <- grepl("^suite_", nm)
nm <- nm[keep]
tv <- gsub("[\t\n ]+", " ", tv[keep])

ver <- system2("dpkg-query",
    c("-W", shQuote("-f=${Version}\n"), "update-manager-core"),
    stdout = TRUE)

writeLines(
    c(
        paste0("# generated by tools/make-uss-fixture.R from ", src_path),
        paste0("# update-manager-core ", ver),
        paste(nm, tv, sep = "\t")
    ),
    "inst/tinytest/fixtures/uss-origin-tuples.tsv"
)
cat("wrote", length(nm), "suite tuples\n")
